### ISSUE TITLE
Symfony 4 - Encrypt the same string for 2 differents encryptage

### ISSUE THREAD

**Issue by gthomasArneo** [mogilvie/EncryptBundle#5]
Hello
I tried your bundle and it works very well.
On the other hand I was wondering how to do a findBy on a thong. Currently if I try to encode a string I end up with 2 different encoding so how to make a find:) 

Here is an example of my code: 
`

    /**
     * @return Response
     */
    public function index(EncryptorInterface $encryptor)
    {
        var_dump($encryptor->encrypt('gthomas'));
        var_dump($encryptor->encrypt('gthomas'));
        $user = $this->getDoctrine()->getRepository(User::class)->findByUsername($encryptor->encrypt('gthomas'));`
Thank you

**Comment by mogilvie** [comment]
Hi,
The encryption processed creates a different encrypted value each time. This is desired behavior. There should be no repeatability of the process which could lead to the encryption being reverse engineered.
If you need to search for a specific encrypted value then you will need to decrypt all entities and perform a filter/matching function.

How you approach this might be dependent on your data set. For instance, one of my app's stores the IP addresses of all successful login attempts. I encrypt the IP address as it is a PersonalData item. However, I also store the last two octets of the IP address in a separate column. The last two items are not sufficient to identify the individual. To find a specific IP address I first query the repository by the last two octets, then search the returned hydrated objects by decrypting the IP address and comparing against the search.

**Comment by mogilvie** [comment]
Further to your specific example.
I use the FosUserBundle for authentication management. The problem is that a user name must be unique, and in order to test uniqueness the username needs to be searchable. Doctrine can't search an encrypted value. FosUserBundle username is not compatible with the PersonalData object for that reason.
Unfortunately, users may choose to use personal information (such as their name or email address) as their username.
So, I would suggest:
1) Assigning the users their username (like banks so when they give you an ID number)
2) Pseudo anonymizing the user login credentials from the more sensitive user data.

The latter would be achieved by having unencrypted user login name on an entity with encrypted foreign key pointing to where the rest of the users data is stored.
